[env:sensecap_rp2040_bridge]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
; UF2 / BOOTSEL flash — see docs/TECHNICAL_CONCEPT.md
; upload_port = /dev/ttyACM0
; monitor_port = /dev/ttyACM0
monitor_speed = 115200

lib_deps =
    bakercp/PacketSerial @ 1.4.0
    adafruit/Adafruit TSL2591 Library @ 1.4.5
    adafruit/Adafruit AS7343 @ 1.1.0
